# Generated by Django 6.0.2 on 2026-03-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunuz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('amateur', 'Amateur'), ('student', 'Student'), ('researcher', 'Researcher'), ('architect', 'Architect'), ('historian', 'Historian'), ('guide', 'Guide')], max_length=30),
        ),
    ]
