# Generated by Django 4.2.29 on 2026-03-16 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment'),
        ),
        migrations.CreateModel(
            name='CommentGem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, default='', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gems', to='posts.comment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='commentgem',
            constraint=models.UniqueConstraint(fields=('comment', 'user_id'), name='unique_gem_per_user_comment'),
        ),
    ]
