# Generated by Django 6.0.2 on 2026-02-27 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kunuz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='location_name',
            new_name='location',
        ),
        migrations.AddField(
            model_name='post',
            name='historical_period',
            field=models.CharField(blank=True, choices=[('prehistory', 'Prehistory'), ('roman', 'Roman'), ('islamic', 'Islamic'), ('ottoman', 'Ottoman'), ('contemporary', 'Contemporary')], max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='monument_type',
            field=models.CharField(blank=True, choices=[('civil', 'Civil'), ('military', 'Military'), ('religious', 'Religious'), ('funerary', 'Funerary')], max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.CharField(blank=True, choices=[('algiers', 'Algiers'), ('oran', 'Oran'), ('constantine', 'Constantine'), ('tlemcen', 'Tlemcen')], max_length=20),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Kunuz.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gems', to='Kunuz.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
