# Generated by Django 6.0.2 on 2026-02-27 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kunuz', '0002_rename_location_name_post_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='post',
            name='historical_period',
            field=models.CharField(blank=True, choices=[('prehistory', 'Prehistory'), ('roman', 'Roman'), ('islamic', 'Islamic'), ('ottoman', 'Ottoman'), ('contemporary', 'Contemporary')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='monument_type',
            field=models.CharField(blank=True, choices=[('civil', 'Civil'), ('military', 'Military'), ('religious', 'Religious'), ('funerary', 'Funerary')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.CharField(blank=True, choices=[('algiers', 'Algiers'), ('oran', 'Oran'), ('constantine', 'Constantine'), ('tlemcen', 'Tlemcen')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='gem',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_gem_per_user_post'),
        ),
    ]
