# Generated by Django 6.0.2 on 2026-02-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kunuz', '0005_remove_post_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertdetails',
            name='current_status',
            field=models.CharField(choices=[('restored', 'Restored'), ('under_intervention', 'Under intervention'), ('destroyed', 'Destroyed'), ('alert', 'Alert')], default='alert', max_length=25),
        ),
    ]
