# Generated by Django 6.0.2 on 2026-02-27 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kunuz', '0007_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='Kunuz.post'),
        ),
    ]
