# Generated by Django 6.0.2 on 2026-03-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kunuz', '0008_alter_save_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('discovery', 'Discovery'), ('visit', 'Visit'), ('question', 'Question'), ('alert', 'Alert'), ('event', 'Event')], max_length=20),
        ),
    ]
