# Generated by Django 4.2.29 on 2026-03-12 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(db_index=True, default='', max_length=24)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('discovery', 'Discovery'), ('visit', 'Visit'), ('question', 'Question'), ('alert', 'Alert'), ('event', 'Event')], max_length=20)),
                ('historical_period', models.CharField(blank=True, choices=[('prehistory', 'Prehistory'), ('roman', 'Roman'), ('islamic', 'Islamic'), ('ottoman', 'Ottoman'), ('contemporary', 'Contemporary')], default='', max_length=20)),
                ('monument_type', models.CharField(blank=True, choices=[('civil', 'Civil'), ('military', 'Military'), ('religious', 'Religious'), ('funerary', 'Funerary')], default='', max_length=20)),
                ('region', models.CharField(blank=True, choices=[('algiers', 'Algiers'), ('oran', 'Oran'), ('constantine', 'Constantine'), ('tlemcen', 'Tlemcen')], default='', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('groups', 'Specific Groups')], default='public', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, default='', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, default='', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gems', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_details', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, default='', max_length=24)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('current_status', models.CharField(choices=[('restored', 'Restored'), ('under_intervention', 'Under intervention'), ('destroyed', 'Destroyed'), ('alert', 'Alert')], default='alert', max_length=25)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_details', to='posts.post')),
            ],
        ),
        migrations.AddConstraint(
            model_name='save',
            constraint=models.UniqueConstraint(fields=('post', 'user_id'), name='unique_save_per_user_post'),
        ),
        migrations.AddConstraint(
            model_name='gem',
            constraint=models.UniqueConstraint(fields=('post', 'user_id'), name='unique_gem_per_user_post'),
        ),
    ]
